name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: '17'
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [17, 21]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Run tests
      run: ./gradlew test -PrunOnCI
    
    - name: Generate test report
      run: ./gradlew jacocoTestReport -PrunOnCI
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./build/reports/jacoco/test/jacocoTestReport.xml
        fail_ci_if_error: true

  sonarqube_analysis:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only run on push to main
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Run SonarQube analysis
      run: ./gradlew sonarqube -PrunOnCI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Run security audit
      run: ./gradlew dependencyCheckAnalyze
    
    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v2
      with:
        languages: java
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  build:
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build application
      run: ./gradlew build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: build/libs/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: [test, security, sonarqube_analysis]
    if: github.event_name == 'push'
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image using Jib
      run: ./gradlew jib

  deploy:
    runs-on: ubuntu-latest
    needs: [build, docker]
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to production
      run: |
        echo "Deployment would happen here"
        echo "This could include:"
        echo "- SSH to production server"
        echo "- Pull latest Docker image"
        echo "- Run deployment script"
        echo "- Perform health checks"
    
    - name: Notify deployment
      if: always()
      run: |
        echo "Deployment completed for ${{ github.sha }}"
